version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8.1
    parameters:
      envvar:
        type: string
    environment:
      EXPECTED_VARIABLE: "Hello!"
      TEST_VARIABLE: << parameters.envvar >>
    steps:
      - checkout
      - run: python3 python/test.py

workflows:
  test:
    jobs:
      - test:
          envvar: ${FROM_PROJECT}
            